version: 0.2 

env:
  variables:
    FUNCTION_NAME: lambda-person
    ALIAS_NAME: lambda-person-version
    BUCKET_NAME: account-a-884069944685-codedeploy-artfacts

phases:
  pre_build: 
    commands: 
      - echo PRE_BUILD no tasks... 
  build: 
    commands: 
      - echo PRE_BUILD no tasks... 
  post_build: 
      commands: 
      - echo POST_BUILD Updating lambda Function... 

      - aws lambda update-function-code --function-name ${FUNCTION_NAME} --s3-bucket ${BUCKET_NAME} --s3-key ${FUNCTION_NAME}/main.zip